import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "../components/AppHeader/AppHeader";
import AppFooter from "../components/AppFooter/AppFooter";
import StoreProvider from "../stores/StoreProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className + " " + "h-svh"}>
          <AppHeader />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
